version: "3"

services:
  python:
    build: ./build/python
    container_name: python
    tty: true
    volumes:
      - ./code:/code
    command: bash -c "pip install --upgrade pip && pip install -r requirements.txt && /bin/bash"
